
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ignyte.whatsshowing;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Wed Oct 28 16:41:35 IST 2009
 * Generated source version: 2.2.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "MovieInformation",
                      portName = "MovieInformationSoap",
                      targetNamespace = "http://www.ignyte.com/whatsshowing",
                      endpointInterface = "com.ignyte.whatsshowing.MovieInformationSoap")
                      
public class MovieInformationSoapImpl implements MovieInformationSoap {

    private static final Logger LOG = Logger.getLogger(MovieInformationSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.ignyte.whatsshowing.MovieInformationSoap#getUpcomingMovies(int  month ,)int  year )*
     */
    public com.ignyte.whatsshowing.ArrayOfUpcomingMovie getUpcomingMovies(int month,int year) { 
        LOG.info("Executing operation getUpcomingMovies");
        System.out.println(month);
        System.out.println(year);
        try {
            com.ignyte.whatsshowing.ArrayOfUpcomingMovie _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ignyte.whatsshowing.MovieInformationSoap#getTheatersAndMovies(java.lang.String  zipCode ,)int  radius )*
     */
    public com.ignyte.whatsshowing.ArrayOfTheater getTheatersAndMovies(java.lang.String zipCode,int radius) { 
        LOG.info("Executing operation getTheatersAndMovies");
        System.out.println(zipCode);
        System.out.println(radius);
        try {
            com.ignyte.whatsshowing.ArrayOfTheater _return = new 
			com.ignyte.whatsshowing.ArrayOfTheater();
			Theater theatre = new Theater();
            theatre.setName("Golden Gate Cinemas");
			theatre.setAddress("Golden Gate Lane");
			Movie movie = new Movie();
			movie.setName("Time changes movie");
			ArrayOfMovie movieArray =  new ArrayOfMovie();
			movieArray.getMovie().add(movie);
		    theatre.setMovies(movieArray);
			_return.getTheater().add(theatre);
            return _return;

        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
